name: MacOS + upstream zlib

on:
  workflow_dispatch:
  push:
  pull_request:
  schedule:
      - cron: '02 02 * * 6'    # Run every Saturday

# upstream build derived from https://github.com/madler/zlib/pull/506


jobs:
  build:

    runs-on: macos-latest

    strategy:
      matrix:
        perl:
          - '5.38'
        zlib-version:
          - v1.2.13
          - v1.2.12
          - v1.2.11
          - develop

    env:
      zlib-source:      ${{ github.workspace }}/upstream-zlib-source
      zlib-install:     ${{ github.workspace }}/upstream-zlib-install
      ZLIB_LIB:         ${{ github.workspace }}/upstream-zlib-install/lib
      ZLIB_INCLUDE:     ${{ github.workspace }}/upstream-zlib-install/include
      ZLIB_VERSION:     ${{ matrix.zlib-version }}
      BUILD_ZLIB:       0
      ZLIB_NG_PRESENT:  0
      USE_ZLIB_NG:      0

    defaults:
      run:
        working-directory: repo

    name: Perl ${{ matrix.perl }} with zlib ${{matrix.zlib-version}}
    steps:

    - uses: actions/checkout@v3
      with:
        path: repo

    - name: Make Paths
      run: |
        mkdir -p ${{ env.zlib-source }}
        mkdir -p ${{ env.zlib-install }}
        mkdir -p ${{ github.workspace }}/repo

    - name: Cache zlib ${{matrix.zlib-version}} ${{ matrix.zlib-native }}
      id: cache-zlib
      uses: actions/cache@v3
      with:
        # NOTE: path doesn't expand variables!
        path: upstream-zlib-install
        key: ${{ runner.os }}-zlib-${{ matrix.zlib-version }}-${{ matrix.zlib-native }}

    - name: Checkout upstream zlib ${{matrix.zlib-version}}
      if:  ( matrix.zlib-version == 'develop' || steps.cache-zlib.outputs.cache-hit != 'true' )
      uses: actions/checkout@v3
      with:
        repository: madler/zlib
        ref: ${{ matrix.zlib-version }}
        path: ${{ env.zlib-source }}

    # - name: Build zlib ${{matrix.zlib-version}}
    #   if: ( matrix.zlib-version == 'develop' || steps.cache-zlib.outputs.cache-hit != 'true' )
    #   run: |
    #     ./configure --prefix ${{ env.zlib-install }}
    #     make
    #     make test
    #     make install
    #     find .
    #   working-directory: ${{ env.zlib-source }}

    - name: Build zlib ${{matrix.zlib-version}}
      if: ( matrix.zlib-version == 'develop' || steps.cache-zlib.outputs.cache-hit != 'true' )
      run: |
        cmake -S . -B . \
          -D CMAKE_INSTALL_PREFIX='${{ env.zlib-install }}' \
          -D CMAKE_BUILD_TYPE=Release \
          -D BUILD_SHARED_LIBS='ON'
        cmake --build . --config Release
        ctest -C Release --output-on-failure --max-width 120
        cmake --install .
        find .
      working-directory: ${{ env.zlib-source }}
      shell: bash

    - name: Show installed zlib files
      run: |
        find .
      shell: bash
      working-directory: ${{ env.zlib-install }}

    - name: Setup perl
      uses: shogo82148/actions-setup-perl@v1
      with:
        perl-version: ${{ matrix.perl }}

    - name: Perl version
      run: perl -V

    #- name: Install dependencies
    #  run: |
    #    cpanm --verbose --installdeps --notest .

    - name: Build
      run: |
        perl Makefile.PL && make

    - name: Test
      run: make test
