name: Windows + upstream zlib

on:
  workflow_dispatch:
  push:
  pull_request:
  schedule:
      - cron: '02 02 * * 6'    # Run every Saturday

# upstream build derived from https://github.com/madler/zlib/pull/506


jobs:
  build:

    runs-on: windows-latest

    strategy:
      matrix:
        perl:
          - '5.36'
        zlib-version:
          - v1.2.13
          - v1.2.12
          - v1.2.11
          - develop


    defaults:
      run:
        shell: bash

    name: Perl ${{ matrix.perl }} with zlib :${{matrix.zlib-version}}
    steps:
    - uses: actions/checkout@v3

    - name: Set Env
      run: |
        echo "zlib-source=${GITHUB_WORKSPACE}/upstream-zlib-source-${{ matrix.zlib-version }}"  >> $GITHUB_ENV
        echo "zlib-install=${HOME}/upstream-zlib-install-${{ matrix.zlib-version }}"            >> $GITHUB_ENV
        echo "ZLIB_LIB=${HOME}/upstream-zlib-install-${{ matrix.zlib-version }}/lib"            >> $GITHUB_ENV
        echo "ZLIB_INCLUDE=${HOME}/upstream-zlib-install-${{ matrix.zlib-version }}/include"    >> $GITHUB_ENV
        echo "ZLIB_VERSION=${{ matrix.zlib-version }}"                                          >> $GITHUB_ENV
        echo "BUILD_ZLIB=0"                                                                     >> $GITHUB_ENV
        echo "ZLIB_NG_PRESENT=0"                                                                >> $GITHUB_ENV
        echo "INCLUDE_PATH=/"                                                                   >> $GITHUB_ENV
        echo "INCLUDE_PATH=/"                                                                   >> $GITHUB_ENV
        echo "LIBRARY_PATH=/"                                                                   >> $GITHUB_ENV
        echo "DESTDIR=${HOME}/upstream-zlib-install-${{ matrix.zlib-version }}"                 >> $GITHUB_ENV

    - name: Checkout upstream zlib ${{matrix.zlib-version}}
      uses: actions/checkout@v3
      with:
        repository: madler/zlib
        ref: ${{ matrix.zlib-version }}
        path: ${{ env.zlib-source }}

    - name: Build zlib ${{matrix.zlib-version}}
      run: |
        env
        echo XXX ${{ env.zlib-install }}
        make -f win32/Makefile.gcc
        make -f win32/Makefile.gcc test
        make -f win32/Makefile.gcc install SHARED_MODE=1
      working-directory: ${{ env.zlib-source }}

    - name: Setup perl
      uses: shogo82148/actions-setup-perl@v1
      with:
        perl-version: ${{ matrix.perl }}

    - name: Perl version
      run: perl -V

    #- name: Install dependencies
    #  run: |
    #    cpanm --verbose --installdeps --notest .

    - name: Backslash
      run: |
        perl -i -pe 's#/#\\#g' $GITHUB_ENV

    - name: Backslash2
      run: |
        env

    - name: Build
      run: |
        perl.exe Makefile.PL && make
      shell: cmd


    - name: Test
      run: make test
      shell: cmd
